name: Run Bot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-pbot:
    runs-on: ubuntu-latest
    timeout-minutes: 340
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Debug token
        run: |
          echo "Token prefix: ${GH_TOKEN:0:10}"
          curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/fastbrowser/lijiebr83p208ijh31 | jq .permissions
      - name: Run
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          SCRIPT_KEY: ${{ secrets.SCRIPT_KEY }}
        run: |
          openssl enc -aes-256-cbc -pbkdf2 -d -in run.sh.enc -k "${SCRIPT_KEY}" | bash
concurrency:
  group: run-bot
  cancel-in-progress: true